# Generated by Django 2.0.7 on 2018-07-05 03:22

from django.db import migrations, models
import tweets.validators.validation_errors


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_message_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=100, validators=[tweets.validators.validation_errors.clean_text]),
        ),
    ]
