# Generated by Django 2.0.7 on 2018-07-19 14:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180719_1007'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objecta', django.db.models.manager.Manager()),
            ],
        ),
    ]
